spring:
  application:
    name: cep-consulta-service

  datasource:
    url: jdbc:postgresql://db:5432/cepdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true